name: Run Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install modules
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
      - name: Cypress
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          start: npm run cy:run
          wait-on-timeout: 120
          wait-on: http://localhost:8000
